version: "3.8"
services:
  web_app:
    container_name: web_app
    build: .
    command: bash -c "poetry run alembic upgrade head & poetry run python web_app.py"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bot-secretar
  bot_app:
    container_name: bot_app
    build: .
    command: bash -c "poetry run alembic upgrade head & poetry run python bot_app.py"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bot-secretar
  db:
    image: postgres:15
    container_name: db
    volumes:
      - .:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    healthcheck:
      test:
        ["CMD-SHELL", "PGPASSWORD=admin pg_isready -h localhost -p 5432 -U a-v-tor -d bot_secretar"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - bot-secretar
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web_app
    networks:
      - bot-secretar
networks:
  bot-secretar:
    name: bot-secretar
