[tool.poetry]
packages = [
    {include = 'bot'},
]
name = "bot-secretar"
version = "1.0.0"
description = "telegram bot"
authors = ["Артем Торшин <avtorca4@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
flake8 = "^4.0.1"
lxml = "^4.9.0"
requests = "^2.28.0"
aiogram = "^2.20"
beautifulsoup4 = "^4.11.1"
prettytable = "^3.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bot-secretar = 'bot.script.start_bot:main'


