"""add timezones

Revision ID: 9d161514cc85
Revises: 335faec11f5a
Create Date: 2025-08-17 13:53:06.660145

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d161514cc85'
down_revision: Union[str, None] = '335faec11f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        'public',
        'timezones',
        ['offset_03', 'offset_05'],
        [
            'offset_00',
            'offset_01',
            'offset_02',
            'offset_03',
            'offset_04',
            'offset_05',
            'offset_06',
            'offset_07',
            'offset_08',
            'offset_09',
            'offset_10',
        ],
        [('time_zones', 'time_zones')],
        False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        'public',
        'timezones',
        [
            'offset_00',
            'offset_01',
            'offset_02',
            'offset_03',
            'offset_04',
            'offset_05',
            'offset_06',
            'offset_07',
            'offset_08',
            'offset_09',
            'offset_10',
        ],
        ['offset_03', 'offset_05'],
        [('time_zones', 'time_zones')],
        True,
    )
    # ### end Alembic commands ###
