"""timezone for reminder

Revision ID: 2e25b3c590d8
Revises: 7fa7797fd244
Create Date: 2025-08-16 01:35:34.541766

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e25b3c590d8'
down_revision: Union[str, None] = '7fa7797fd244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    op.alter_column(
        'reminders',
        'datetime_reminder',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'reminders',
        'datetime_reminder',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.create_table(
        'accounts',
        sa.Column(
            'id',
            sa.INTEGER(),
            sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column('client', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('amounr', sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='accounts_pkey'),
    )
    # ### end Alembic commands ###
