"""add model TimeZone

Revision ID: 335faec11f5a
Revises: 2e25b3c590d8
Create Date: 2025-08-16 19:36:52.984254

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '335faec11f5a'
down_revision: Union[str, None] = '2e25b3c590d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'time_zones',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('time_zones', postgresql.ENUM('offset_03', 'offset_05', name='timezones'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('time_zones'),
    )
    op.add_column('users', sa.Column('time_zones_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'time_zones', ['time_zones_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'time_zones_id')
    op.drop_table('time_zones')
    # ### end Alembic commands ###
