"""add table reminders

Revision ID: 7fa7797fd244
Revises: 190bc521e750
Create Date: 2025-03-07 21:26:08.265117
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fa7797fd244'
down_revision: Union[str, None] = '190bc521e750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reminders',
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column(
            'type_expenses',
            postgresql.ENUM(
                'very_important',
                'important',
                'doesnot_matter',
                name='reminderlevel',
            ),
            nullable=False,
        ),
        sa.Column('datetime_reminder', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_telegram_id'],
            ['users.telegram_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    # ### end Alembic commands ###
