"""Добавлены тпы расходов

Revision ID: 5c1040edeb7c
Revises: da7247b73fd9
Create Date: 2026-09-29 13:35:09.381985

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c1040edeb7c'
down_revision: Union[str, None] = 'da7247b73fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        'public',
        'typeexpenses',
        ['CLOTH', 'ELECTRONICS', 'ENTERTAINMENT', 'FOOD', 'HEALTH', 'OTHER', 'PRESENT', 'TAXES', 'TRANSPORT'],
        [
            'CAFEANDFASTFOOD',
            'CLOTH',
            'ELECTRONICS',
            'ENTERTAINMENT',
            'FOOD',
            'HEALTH',
            'INVESTMENTS',
            'MAJORPURCHASES',
            'OTHER',
            'PRESENT',
            'SPORT',
            'TAXES',
            'TRANSPORT',
            'TRAVEL',
        ],
        [('expenses', 'type_expenses')],
        False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        'public',
        'typeexpenses',
        [
            'CAFEANDFASTFOOD',
            'CLOTH',
            'ELECTRONICS',
            'ENTERTAINMENT',
            'FOOD',
            'HEALTH',
            'INVESTMENTS',
            'MAJORPURCHASES',
            'OTHER',
            'PRESENT',
            'SPORT',
            'TAXES',
            'TRANSPORT',
            'TRAVEL',
        ],
        ['CLOTH', 'ELECTRONICS', 'ENTERTAINMENT', 'FOOD', 'HEALTH', 'OTHER', 'PRESENT', 'TAXES', 'TRANSPORT'],
        [('expenses', 'type_expenses')],
        True,
    )
    # ### end Alembic commands ###
